# Generated by Django 4.2.3 on 2023-07-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Postes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pdf_file',
        ),
    ]
